# Generated by Django 4.0.6 on 2022-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=240, verbose_name='Book Name')),
                ('words', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Chapter Created Date')),
            ],
        ),
    ]
